spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/cartoni_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${BL_DB_USER:root}
spring.datasource.password=${BL_DB_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update